### ISSUE TITLE
Possivel erro no calculo do Earning Yield

### ISSUE THREAD

**Issue by Edresson** [marinellirubens/magic_formula#1]
Olá Rubens,  

Primeiramente parabéns pelo projeto, código muito bem comentado e organizado :). 

Acredito que a formula correta para o calculo do Earning Yield seja: (self.ebit / self.tev)  e não   como está [aqui](https://github.com/marinellirubens/magic_formula/blob/28fa58f6919b9ad2276eb71735a6d19562fa7ce8/magic_formula/magic_formula_core.py#L252)  (self.tev / self.ebit). Veja [esse post onde o  Ramiro do CDV  fala sobre a  Magic Formula](https://clubedovalor.com.br/blog/magic-formula/) e define o  Earning Yield (a menos que eu tenha entendido errado o livro também define desse modo). Do modo que está atualmente, você está calculando o inverso do Earning Yield (algo muito próximo da P/L), portanto a interpretação deve  ser oposta também (menor melhor)  e não maior melhor como está. 

Você acha que isso é uma inconsistência ou eu entendi algo errado?

Atenciosamente,
Edresson Casanova.

**Comment by marinellirubens** [comment]
Olá Edresson, 

Muito obrigado por pontuar isso, de fato existia essa inconsistência mesmo devo ter me confundido na hora, eu fiz um commit pra corrigir isso e mais umas coisas. [Commit](https://github.com/marinellirubens/magic_formula/commit/b3a43f32bc05906b71b19754c19a269c1aa17b01)

Atenciosamente,
Rubens Marinelli Ferreira.
